### ISSUE TITLE
Content not displayed on iPhone and iPad

### ISSUE THREAD

**Issue by svaenn** [globaldevopsexperience/event-portal#5]
Using Safari on my iPhone and my iPad (latest Os) the portal only displays the footer, not the logo and text.
Safari on Desktop is ok.

**Comment by svaenn** [comment]
![IMG_72CB2B94D30C-1](https://github.com/globaldevopsexperience/event-portal/assets/18374548/1ce776d1-87ac-442a-abe9-687df12618f9)

**Comment by mivano** [comment]
Thanks for reporting, we will take a look at making it more mobile friendly.

**Comment by mivano** [comment]
It is looking fine on my iPhone. So I cant really find any issues (anymore). I m closing this one for now.
